Eburgess gradio lab
GoogleCloudPlatform/devrel-demos pull request #234
Opened 2024-08-05 12:23 UTC by EmanuelB25

adding Gradio chatbot

2024-08-05 14:16 UTC, rsamborski requested changes
Thanks for the PR. I suggest to move it to a different folder, as currently you're putting it together with Sampath's streamlit bot. Potential location could be: `ai-ml/gemini-chatbot-app-gradio`, `ai-ml/gemini-chatbot-gradio` or something similar.

Couple other suggestions inline.

2024-08-05 14:16 UTC, rsamborski commented on ai-ml/gemini-chatbot-app/gradio/Dockerfile
> +# Dirty fix for https://github.com/gradio-app/gradio/pull/7707 regression
```suggestion
# Dirty fix, won't be necessary when https://github.com/gradio-app/gradio/pull/8962 gets into Gradio release 
```

2024-08-05 14:16 UTC, rsamborski commented on ai-ml/gemini-chatbot-app/gradio/deploy.sh
> +PROJECT=emanuel-ai
```suggestion
PROJECT=<YOUR-PROJECT-ID>
```

2024-08-05 14:16 UTC, rsamborski commented on ai-ml/gemini-chatbot-app/gradio/deploy.sh
> +# Google Cloud Project
```suggestion
# @TODO Replace <YOUR-PROJECT-ID> with your Google Cloud Project ID
```

2024-08-06 02:40 UTC, EmanuelB25 commented on ai-ml/gemini-chatbot-app/gradio/deploy.sh
> +# Google Cloud Project
updated. Thanks I missed this.

2024-08-06 02:40 UTC, EmanuelB25 commented on ai-ml/gemini-chatbot-app/gradio/deploy.sh
> +PROJECT=emanuel-ai
updated. Thanks I missed this.

2024-08-06 02:40 UTC, EmanuelB25 commented on ai-ml/gemini-chatbot-app/gradio/Dockerfile
> +# Dirty fix for https://github.com/gradio-app/gradio/pull/7707 regression
updated. Thanks I missed this.

2024-08-06 02:40 UTC, EmanuelB25 commented
I did a push to fix issues. Please review.

2024-08-07 23:31 UTC, thagomizer commented
Can you please add Apache license headers and then I'll merge.

2024-08-08 08:02 UTC, rsamborski commented
> Can you please add Apache license headers and then I'll merge.

@thagomizer Good catch. 
@EmanuelB25 Please also remember to remove duplicate files in folder `ai-ml/gemini-chatbot-app/gradio`, you should only preserve files in `ai-ml/gemini-chatbot-app-gradio`.

2024-08-08 11:41 UTC, EmanuelB25 commented
Updated. @rsamborski

2024-08-08 13:18 UTC, rsamborski approved these changes

2024-09-03 18:46 UTC, merged